const TRANSFORM_OPTIONS = {
  angle: "a_",
  audioCodec: "ac_",
  audioFrequency: "af_",
  aspectRatio: "ar_",
  background: "b_",
  bitRate: "br_",
  border: "bo_",
  color: "co_",
  colorSpace: "cs_",
  crop: "c_",
  customFunction: "fn_",
  defaultImage: "d_",
  delay: "dl_",
  density: "dn_",
  duration: "du_",
  dpr: "dpr_",
  effect: "e_",
  endOffset: "eo_",
  fetchFormat: "f_",
  format: "f_",
  flags: "fl_",
  fps: "fps_",
  gravity: "g_",
  height: "h_",
  if: "if_",
  keyframeInterval: "ki_",
  offset: "-_",
  opacity: "o_",
  overlay: "l_",
  page: "p_",
  quality: "q_",
  radius: "r_",
  startOffset: 'so_',
  streamingProfile: "sp_",
  transformation: "t_",
  underlay: "u_",
  variable: "$_",
  videoCodec: "vc_",
  videoSampling: "vs_",
  width: "w_",
  x: "x_",
  y: "y_",
  zoom: "z_"
};

export default TRANSFORM_OPTIONS;